2020-09-18 16:13:46,337 [ERROR]: #  **** Email sent failure ****
Traceback (most recent call last):
  File "D:/sktest/common/emailtool.py", line 43, in send_email
    server.login(user, password)
  File "D:\Program Files (x86)\Python\Python37\lib\smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "D:\Program Files (x86)\Python\Python37\lib\smtplib.py", line 631, in auth
    (code, resp) = self.docmd("AUTH", mechanism + " " + response)
TypeError: can only concatenate str (not "bytes") to str
2020-09-18 16:15:46,839 [ERROR]: #  **** Email failed to send without configured email account and password。。。 ****
NoneType: None
2020-09-18 16:16:30,112 [ERROR]: #  **** Email failed to send without configured email account and password。。。 ****
2020-09-18 16:18:11,005 [INFO]: #  **** Email sent successfully ****
